# Generated by Django 2.2.6 on 2019-11-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('articlesWritten', models.DecimalField(decimal_places=1, max_digits=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(default='this is a cool article')),
                ('datePosed', models.DateField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsArticles.Writer')),
            ],
        ),
    ]
