# Generated by Django 2.2.6 on 2019-11-03 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsArticles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='datePosed',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='articlesWritten',
        ),
        migrations.AddField(
            model_name='article',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(),
        ),
    ]
